const crypto = require("crypto");
const {
  PutObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  DeleteObjectCommand,
} = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

const { s3Client, S3_BUCKET } = require("../config/s3");
const { postUploadLimits } = require("./constants");

// Phase 4 — the object-storage half of the posts feature.
//
// THE CENTRAL DESIGN DECISION: image bytes never pass through this Node process.
//
// The obvious implementation of "upload a photo" is multipart/form-data to an
// Express route (multer or similar), which then forwards the buffer to S3. That
// works, and it is wrong at any scale, for reasons worth being precise about
// rather than hand-waving as "it's slow":
//
//   1. It doubles every byte's journey. The client uploads to us, then we upload
//      to S3 — so a 5MB post costs 5MB of ingress AND 5MB of egress on our
//      instance, and the user waits for both hops serially before getting a
//      response.
//   2. It holds an event-loop-bound process hostage for the duration. Node is
//      single-threaded; a request that spends 8 seconds streaming a photo over a
//      phone's uplink is 8 seconds of a connection, a request slot, and buffer
//      memory held open. A few hundred concurrent uploaders on bad connections is
//      not unusual traffic, and it is enough to starve every other route on the
//      instance — the API gets slow for people who are not uploading anything.
//   3. Buffering means memory scales with concurrency times file size, so the
//      failure mode under an upload spike is the process being OOM-killed.
//   4. It puts a request timeout between the user and a successful upload. Every
//      layer in front of us (load balancer, proxy) has one, and slow mobile
//      uploads are exactly the requests that hit it.
//
// A presigned URL removes the middle hop entirely. We sign a URL with our
// credentials and hand it to the client; the client PUTs the bytes straight to S3.
// Our involvement is two small JSON requests that never touch the payload, so an
// upload's cost to us is constant regardless of image size, and S3's own
// throughput and durability do the work it is built for.
//
// The price is that "upload" stops being one atomic operation and becomes three
// steps across two systems, which is where all the interesting edge cases below
// come from. Every one of them is a consequence of that trade, and taking it is
// still correct.

// Bucket-relative key for a new upload: `posts/<userId>/<32 hex chars>.<ext>`.
//
// Three deliberate properties:
//
//   - The user id is a PREFIX, not a suffix. S3 has no directories; a key prefix
//     is the only grouping primitive there is, and it is what IAM policies,
//     lifecycle rules and bulk deletes can address. "Delete everything this user
//     uploaded" (a GDPR erasure request, or cleaning up a banned account) is a
//     prefix operation with this layout and a full-bucket listing without it.
//   - The filename is server-generated randomness, never the client's. A
//     client-supplied filename is a path-traversal vector (`../../`), a collision
//     risk (every phone calls it IMG_0001.jpg), and an information leak. 16 random
//     bytes also make keys unguessable, which matters because an object key is
//     part of the read URL.
//   - The extension comes from the ALLOWED list, not from the client's filename.
//     It is cosmetic — S3 serves by stored Content-Type, not by extension — but it
//     keeps the bucket browsable by a human debugging it.
const EXTENSION_BY_TYPE = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

const buildUploadKey = (userId, contentType) =>
  `posts/${userId}/${crypto.randomBytes(16).toString("hex")}.${
    EXTENSION_BY_TYPE[contentType]
  }`;

// The thumbnail's key is DERIVED from the original's, not independently random.
//
// That derivation is what makes the pair self-describing in the bucket: given any
// thumbnail you can name its original and vice versa, without consulting Mongo. It
// matters for the failure case that actually happens — a thumbnail worker that
// crashed mid-batch, leaving posts whose thumbnailKey is still null. A backfill can
// then be driven entirely from the Post collection, and re-running it is
// idempotent because the key it computes is the same key it computed last time
// (a random one would orphan the previous attempt's object on every retry).
//
// Always .webp regardless of the original's format: the thumbnail is generated by
// us for display only, so there is no reason to carry a legacy format forward, and
// webp is materially smaller than JPEG at equivalent quality.
const buildThumbnailKey = (imageKey) =>
  `thumbs/${imageKey.replace(/^posts\//, "").replace(/\.[^.]+$/, "")}.webp`;

// ---------------------------------------------------------------------------
// Presigned upload
// ---------------------------------------------------------------------------

// Sign a PUT the client can use exactly once, for exactly this object.
//
// `signableHeaders: ["content-type"]` is not optional decoration, and finding out
// why cost a verification round worth writing down.
//
// Passing `ContentType` to PutObjectCommand looks like it should constrain the
// upload. It does not. By default the presigner signs only the `host` header —
// the generated URL comes back with `X-Amz-SignedHeaders=host` — so the
// ContentType is simply absent from the signature, and the URL will accept a PUT
// declaring ANY type. Verified against MinIO before this line existed: a URL
// signed for image/jpeg accepted a `Content-Type: text/plain` PUT with a 200, and
// the object landed stored as text/plain.
//
// Adding content-type to the signable set puts it in the signature
// (`X-Amz-SignedHeaders=content-type;host`), and the mismatched PUT then fails
// with 403 SignatureDoesNotMatch — refused by the object store, before the bytes
// are stored. That is the difference between a declared intention and an enforced
// constraint, and it is invisible unless you actually try to violate it.
//
// Note what it still does NOT do: it binds the LABEL, not the content. A client
// can send `Content-Type: image/jpeg` with any bytes it likes. The only thing
// that parses the actual bytes is sharp, in the thumbnail worker.
//
// WHAT THIS CANNOT DO, and it is the most important limitation in the flow:
// a presigned PUT cannot cap the object's SIZE. The size is not known at signing
// time and there is no signable header that constrains it — `ContentLength` in the
// signed command would pin it to one exact value, which a client cannot know
// before choosing a file. So a presigned PUT URL is, for its lifetime, permission
// to write an object of ANY size to that key.
//
// Three ways to deal with that, and why we chose the third:
//
//   a) Presigned POST (`createPresignedPost`) instead of PUT. A POST policy DOES
//      support a `content-length-range` condition, enforced by S3 at upload time —
//      it is the only option that rejects oversized bytes before they are stored.
//      Rejected because it needs another dependency, and because the client side
//      becomes a multipart form with a dozen policy fields rather than a one-line
//      `fetch(url, {method: "PUT", body: file})`. Worth naming as the more correct
//      answer if uploads were ever untrusted or unmetered.
//   b) Trust the client's pre-upload size check. Not a control at all — the client
//      is the thing we are protecting the bucket from.
//   c) Verify after the fact, at claim time, with a HeadObject — and refuse to
//      create the post, deleting the object, if it is oversized. This is what we
//      do (see verifyUploadedObject below and POST /posts).
//
// The honest limitation of (c): the oversized bytes were already transferred and
// stored before we noticed, so it does not protect against bandwidth or transient
// storage cost — only against an oversized object becoming a permanent, servable
// post. Given a 5-minute URL TTL, issued only to an authenticated user, for a key
// only they can write, that residual exposure is one oversized object per
// deliberate attempt by someone with an account. Acceptable; (a) is the upgrade
// path if it stops being.
const createUploadUrl = async (userId, contentType) => {
  const key = buildUploadKey(userId, contentType);

  const url = await getSignedUrl(
    s3Client,
    new PutObjectCommand({
      Bucket: S3_BUCKET,
      Key: key,
      ContentType: contentType,
    }),
    {
      expiresIn: postUploadLimits.UPLOAD_URL_TTL_SECONDS,
      signableHeaders: new Set(["content-type"]),
    }
  );

  return { key, url, expiresIn: postUploadLimits.UPLOAD_URL_TTL_SECONDS };
};

// ---------------------------------------------------------------------------
// Presigned read
// ---------------------------------------------------------------------------

// Why reads are signed too, instead of just making the bucket public.
//
// A public bucket would make this function unnecessary and the feed cheaper to
// render — but posts in this app are visible only to the author's accepted
// connections (GET /posts/feed enforces that), and a public object URL is
// readable by anyone who has it, forever. The access rule would then hold in the
// API and not in the storage layer, so a single leaked or shared URL would bypass
// the connection graph completely. An access control that only one of two doors
// enforces is not an access control.
//
// Signed GETs keep the bucket private and make every read URL a short-lived
// capability: it expires, so a leaked URL stops working, and it is minted only
// after the API has already checked that this viewer is allowed to see this post.
//
// The cost, stated plainly: URLs are per-viewer and time-bound, so they are not
// shared-cacheable by a CDN the way a stable public URL would be. The production
// answer to that is CloudFront with signed cookies or an origin-access identity —
// same private-bucket property, cached at the edge. That is infrastructure
// configuration rather than application code, which is why it is documented here
// instead of implemented: nothing in this module would change.
const createViewUrl = (key) =>
  getSignedUrl(s3Client, new GetObjectCommand({ Bucket: S3_BUCKET, Key: key }), {
    expiresIn: postUploadLimits.VIEW_URL_TTL_SECONDS,
  });

// ---------------------------------------------------------------------------
// Verification and cleanup
// ---------------------------------------------------------------------------

// Does this object exist, and is it within our limits?
//
// HeadObject fetches an object's METADATA only — size, content type, etag — with
// no body transfer, so this is cheap regardless of how large the object is. That
// is the property that makes post-hoc verification viable at all: checking a 5MB
// upload's size does not cost 5MB.
//
// Returns a discriminated result rather than throwing, because "the client never
// actually uploaded" and "the client uploaded something too big" are both ordinary
// client errors that POST /posts turns into 4xx responses, not exceptions.
const verifyUploadedObject = async (key) => {
  let head;
  try {
    head = await s3Client.send(
      new HeadObjectCommand({ Bucket: S3_BUCKET, Key: key })
    );
  } catch (err) {
    // S3 answers a HEAD on a missing key with 404 and an empty body, so there is
    // no error Code to match on the way there is for GET (NoSuchKey) — the status
    // code is the only signal. Checked via both the SDK's metadata and the
    // legacy `name` so this does not depend on one SDK version's error shape.
    const status = err?.$metadata?.httpStatusCode;
    if (status === 404 || err?.name === "NotFound") {
      return { ok: false, reason: "missing" };
    }
    // Anything else (credentials, network, bucket policy) is OUR problem, not the
    // client's, and must not be reported as "you didn't upload the file".
    throw err;
  }

  if (head.ContentLength > postUploadLimits.MAX_IMAGE_BYTES) {
    return { ok: false, reason: "too_large", size: head.ContentLength };
  }

  // Load-bearing, not belt-and-braces — and it was belt-and-braces until the
  // verification above proved otherwise.
  //
  // Before content-type joined the signed headers, a client could take a URL
  // signed for image/jpeg and PUT with any Content-Type it liked; this check was
  // the only thing standing between that and a post. The signature now refuses
  // the mismatch at the object store, which makes this the second of two
  // independent barriers rather than the only one. Kept deliberately: it is what
  // catches the case where a signing change silently stops pinning the header
  // again, which is exactly the regression that would otherwise be invisible.
  if (!postUploadLimits.ALLOWED_IMAGE_TYPES.includes(head.ContentType)) {
    return { ok: false, reason: "bad_type", contentType: head.ContentType };
  }

  // Note what is NOT verified here: that the bytes are actually an image. A
  // declared Content-Type is a claim, and HeadObject only ever returns the claim —
  // nothing short of reading the bytes can tell an actual JPEG from a renamed
  // executable. That check does happen, just not here: the thumbnail worker opens
  // every uploaded object with sharp, which parses the real container, and a
  // non-image fails there. See src/workers/thumbnailWorker.js.
  return { ok: true, size: head.ContentLength, contentType: head.ContentType };
};

// Best-effort delete. Used for two distinct cleanups:
//   - an object that failed verification at claim time (oversized/wrong type), and
//   - both objects when a post is deleted.
//
// Never throws. The caller is always in the middle of completing something the
// user asked for, and a storage delete that fails must not turn a successful
// operation into an error. What it leaves behind is an unreferenced object, which
// costs storage and nothing else, and which the bucket lifecycle rule described in
// docs/phase-4.md is the systematic answer to.
const deleteObjectQuietly = async (key) => {
  if (!key) return;
  try {
    await s3Client.send(
      new DeleteObjectCommand({ Bucket: S3_BUCKET, Key: key })
    );
  } catch (err) {
    console.error(`[postStorage] failed to delete ${key}:`, err.message);
  }
};

// ---------------------------------------------------------------------------
// Byte access, for the thumbnail worker only
// ---------------------------------------------------------------------------

// This is the ONE place image bytes enter a Node process — and it is deliberately
// not an API process. The thumbnail worker runs in the separate `npm run worker`
// deployment (src/workers/index.js), so the memory and CPU cost of decoding and
// resizing images lands somewhere that no user is waiting on and that scales
// independently of the API.
//
// `transformToByteArray()` buffers the whole object, which is the honest thing to
// do here: sharp's resize needs the full image, and images are bounded to 5MB by
// the claim-time check, so the buffer is bounded too. An unbounded-size input
// would need a streaming pipeline instead.
const getObjectBuffer = async (key) => {
  const response = await s3Client.send(
    new GetObjectCommand({ Bucket: S3_BUCKET, Key: key })
  );
  return Buffer.from(await response.Body.transformToByteArray());
};

const putObject = async (key, body, contentType) => {
  await s3Client.send(
    new PutObjectCommand({
      Bucket: S3_BUCKET,
      Key: key,
      Body: body,
      ContentType: contentType,
    })
  );
  return key;
};

module.exports = {
  buildUploadKey,
  buildThumbnailKey,
  createUploadUrl,
  createViewUrl,
  verifyUploadedObject,
  deleteObjectQuietly,
  getObjectBuffer,
  putObject,
};
